#!/usr/bin/env python3
"""PreToolUse hook (INV-0000-3).

Blocks Claude Code's file tools from editing generated ADR rules, editing accepted ADRs, and
changing any ADR's status. Exit code 2 blocks the tool call and shows stderr to Claude.
Standard library only, so it runs without the project environment.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ADR_FILE = re.compile(r"^docs/adr/\d{4}-[^/]+\.md$")
STATUS = re.compile(r"^status:\s*([a-z]+)", re.MULTILINE)
GENERATED = ".claude/rules/adr/"


def find_checkout(start: Path, marker: str) -> Path | None:
    """Nearest directory at or above start that holds this repository's hook `marker`.

    Works for the main checkout and for every git worktree of it. Claude Code keeps
    CLAUDE_PROJECT_DIR at the checkout where the session started even after Claude moves into a
    worktree, so hooks locate the checkout from the file or directory they act on instead.
    """
    for directory in (start, *start.parents):
        if (directory / ".claude" / "hooks" / marker).is_file():
            return directory
    return None


def frontmatter_status(text: str) -> str | None:
    """Return the status in an ADR's frontmatter, if any."""
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    match = STATUS.search(text[4:end] if end != -1 else text[4:])
    return match.group(1) if match else None


def written_statuses(tool_input: dict[str, object]) -> set[str]:
    """Statuses that a Write, Edit or MultiEdit call would put into the file."""
    chunks: list[str] = []
    for key in ("content", "new_string"):
        value = tool_input.get(key)
        if isinstance(value, str):
            chunks.append(value)
    edits = tool_input.get("edits")
    if isinstance(edits, list):
        for edit in edits:
            if isinstance(edit, dict):
                value = edit.get("new_string")
                if isinstance(value, str):
                    chunks.append(value)
    return {match.group(1) for chunk in chunks for match in STATUS.finditer(chunk)}


def block(message: str) -> int:
    print(message, file=sys.stderr)
    return 2


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0
    if not isinstance(payload, dict):
        return 0
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return 0
    raw = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(raw, str) or not raw:
        return 0
    base = Path(payload.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or ".")
    target = Path(raw)
    if not target.is_absolute():
        target = base / target
    target = target.resolve()
    root = find_checkout(target.parent, "protect_adrs.py")
    if root is None:
        return 0
    rel = target.relative_to(root).as_posix()
    if rel.startswith(GENERATED):
        return block(
            f"Blocked: {rel} is generated by scripts/gen_adr_rules.py. Edit the ADR under "
            "docs/adr/ and run `uv run python scripts/gen_adr_rules.py`."
        )
    if not ADR_FILE.match(rel):
        return 0
    current = frontmatter_status(target.read_text(encoding="utf-8")) if target.is_file() else None
    if current == "accepted":
        return block(
            f"Blocked: {rel} is accepted, and accepted ADRs change only by supersession. Draft a "
            "new proposed ADR that supersedes it (see docs/adr/README.md). Only the owner changes "
            "an ADR's status."
        )
    wanted = written_statuses(tool_input) - {"proposed"}
    if wanted:
        return block(
            f"Blocked: this edit would set the status of {rel} to {', '.join(sorted(wanted))}. "
            "New and revised ADRs stay proposed; only the owner changes an ADR's status."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
