"""Generate path-scoped Claude Code rules from ADR frontmatter (ADR-0000, INV-0000-2).

Writes .claude/rules/adr/<adr file name> for every proposed or accepted ADR, with the ADR's
applies_to globs as the rule's `paths:`. With --check, only reports drift (exit status 1).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import adr_tools
from adr_tools import Adr

ROOT = Path(__file__).resolve().parents[1]
HEADER = (
    "<!-- Generated by scripts/gen_adr_rules.py from {source}. "
    "Do not edit: change the ADR and regenerate. -->"
)


def render_rule(adr: Adr) -> str:
    lines = ["---", "paths:"]
    lines += [f'  - "{pattern}"' for pattern in adr.applies_to]
    lines += ["---", HEADER.format(source=adr.rel_path), ""]
    lines += [f"# {adr.id} ({adr.status}): {adr.title}", ""]
    if adr.status == "accepted":
        lines.append("Binding for the files that loaded this rule.")
    else:
        lines.append(
            "Proposed, not yet binding. Treat it as the current direction, and ask the owner "
            "before implementing anything that answers one of its open questions."
        )
    lines += ["", adr.summary, ""]
    if adr.invariants:
        lines.append("Invariants:")
        for invariant in adr.invariants:
            lines.append(f"- {invariant.id}: {invariant.text}")
        lines.append("")
    if adr.open_questions:
        lines += ["Open questions: " + ", ".join(adr.open_questions) + ".", ""]
    lines.append(f"Full record: `{adr.rel_path}`. Enforcement: `{adr_tools.ENFORCEMENT_FILE}`.")
    return "\n".join(lines) + "\n"


def expected_rules(adrs: list[Adr]) -> dict[str, str]:
    return {
        f"{adr_tools.GENERATED_RULES_DIR}/{adr.slug}.md": render_rule(adr)
        for adr in adrs
        if adr.status in adr_tools.ACTIVE_STATUSES
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Claude Code rules from ADRs.")
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    adrs, errors = adr_tools.load_adrs(root)
    if errors:
        for error in errors:
            print(f"error: {error}")
        return 2
    expected = expected_rules(adrs)
    rules_dir = root / adr_tools.GENERATED_RULES_DIR
    existing: dict[str, str] = {}
    if rules_dir.is_dir():
        for path in sorted(rules_dir.glob("*.md")):
            existing[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8")
    missing = sorted(set(expected) - set(existing))
    extra = sorted(set(existing) - set(expected))
    stale = sorted(p for p in expected if p in existing and existing[p] != expected[p])
    if args.check:
        for label, paths in (("missing", missing), ("stale", stale), ("extra", extra)):
            for path in paths:
                print(f"{label}: {path}")
        if missing or stale or extra:
            print("Run: uv run python scripts/gen_adr_rules.py")
            return 1
        return 0
    rules_dir.mkdir(parents=True, exist_ok=True)
    for path in missing + stale:
        (root / path).write_text(expected[path], encoding="utf-8")
    for path in extra:
        (root / path).unlink()
    print(
        f"{len(expected)} rules: {len(missing)} written, {len(stale)} updated, {len(extra)} removed"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
